// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.MasterPages {

    public partial class SiteMaster {

        protected global::System.Web.UI.WebControls.Panel pnlGuest;

        protected global::System.Web.UI.WebControls.Panel pnlUser;

        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;

        protected global::System.Web.UI.WebControls.HiddenField hdnNewsletterEmail;

        protected global::System.Web.UI.WebControls.Button btnSubscribeServer;
    }
}
