// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Cart class
    /// </summary>
    public partial class Cart {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// pnlCartEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCartEmpty;
        
        /// <summary>
        /// pnlCartContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCartContent;
        
        /// <summary>
        /// gvCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCart;
        
        /// <summary>
        /// lblSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        
        /// <summary>
        /// txtCoupon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCoupon;
        
        /// <summary>
        /// btnApplyCoupon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyCoupon;
        
        /// <summary>
        /// lblCouponMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCouponMsg;
        
        /// <summary>
        /// pnlDiscountRow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDiscountRow;
        
        /// <summary>
        /// lblCouponCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCouponCode;
        
        /// <summary>
        /// lblDiscountAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscountAmount;
        
        /// <summary>
        /// lblTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTax;
        
        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;
        
        /// <summary>
        /// btnCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCheckout;
    }
}
