// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Checkout class
    /// </summary>
    public partial class Checkout {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;
        
        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;
        
        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        
        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        
        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        
        /// <summary>
        /// txtState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;
        
        /// <summary>
        /// txtZip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZip;
        
        /// <summary>
        /// rblPayment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblPayment;
        
        /// <summary>
        /// pnlCardDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCardDetails;
        
        /// <summary>
        /// txtCardName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardName;
        
        /// <summary>
        /// txtCardNum control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardNum;
        
        /// <summary>
        /// txtCardExp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardExp;
        
        /// <summary>
        /// txtCardCVV control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardCVV;
        
        /// <summary>
        /// pnlUPIDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUPIDetails;
        
        /// <summary>
        /// txtUPIID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUPIID;
        
        /// <summary>
        /// rptSummaryItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSummaryItems;
        
        /// <summary>
        /// lblSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        
        /// <summary>
        /// pnlDiscountRow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDiscountRow;
        
        /// <summary>
        /// lblDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscount;
        
        /// <summary>
        /// lblTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTax;
        
        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;
        
        /// <summary>
        /// btnPlaceOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
    }
}
