// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Collections class
    /// </summary>
    public partial class Collections {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// rptCollections control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCollections;
    }
}
