// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Dashboard class
    /// </summary>
    public partial class Dashboard {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// lblUserSidebarName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserSidebarName;
        
        /// <summary>
        /// lblUserSidebarEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserSidebarEmail;
        
        /// <summary>
        /// lnkTabProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTabProfile;
        
        /// <summary>
        /// lnkTabOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTabOrders;
        
        /// <summary>
        /// lnkTabWishlist control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTabWishlist;
        
        /// <summary>
        /// pnlProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        
        /// <summary>
        /// pnlProfileSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProfileSuccess;
        
        /// <summary>
        /// pnlProfileError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProfileError;
        
        /// <summary>
        /// lblProfileError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileError;
        
        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        
        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        
        /// <summary>
        /// txtState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;
        
        /// <summary>
        /// txtZip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZip;
        
        /// <summary>
        /// btnUpdateProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdateProfile;
        
        /// <summary>
        /// pnlOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOrders;
        
        /// <summary>
        /// rptOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOrders;
        
        /// <summary>
        /// pnlNoOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoOrders;
        
        /// <summary>
        /// pnlWishlist control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlWishlist;
        
        /// <summary>
        /// rptWishlist control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptWishlist;
        
        /// <summary>
        /// pnlNoWishlist control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoWishlist;
    }
}
