// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Home class
    /// </summary>
    public partial class Home {
        
        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content HeadContent;
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// ScriptsContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content ScriptsContent;
        
        /// <summary>
        /// rptFeatured control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFeatured;
        
        /// <summary>
        /// rptNewArrivals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptNewArrivals;
        
        /// <summary>
        /// rptBestSellers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBestSellers;
        
        /// <summary>
        /// rptBrands control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBrands;
    }
}
