// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// OrderSuccess class
    /// </summary>
    public partial class OrderSuccess {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// lblOrderID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderID;
        
        /// <summary>
        /// lblDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDate;
        
        /// <summary>
        /// lblPayment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPayment;
        
        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;
    }
}
