// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// ProductDetail class
    /// </summary>
    public partial class ProductDetail {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// lblBreadcrumbName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBreadcrumbName;
        
        /// <summary>
        /// pnlProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProduct;
        
        /// <summary>
        /// imgProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProduct;
        
        /// <summary>
        /// lblBrand control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBrand;
        
        /// <summary>
        /// lblName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblName;
        
        /// <summary>
        /// lblRatingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRatingCount;
        
        /// <summary>
        /// lblPriceOriginal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPriceOriginal;
        
        /// <summary>
        /// lblPriceCurrent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPriceCurrent;
        
        /// <summary>
        /// lblDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscount;
        
        /// <summary>
        /// badgeStock control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeStock;
        
        /// <summary>
        /// lblDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDescription;
        
        /// <summary>
        /// ddlQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlQty;
        
        /// <summary>
        /// btnAddToCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddToCart;
        
        /// <summary>
        /// lblCartMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCartMessage;
        
        /// <summary>
        /// lblSpecCase control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecCase;
        
        /// <summary>
        /// lblSpecWater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecWater;
        
        /// <summary>
        /// lblSpecMovement control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecMovement;
        
        /// <summary>
        /// lblSpecDial control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecDial;
        
        /// <summary>
        /// lblSpecGlass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecGlass;
        
        /// <summary>
        /// lblSpecBand control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecBand;
        
        /// <summary>
        /// lblSpecWarranty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpecWarranty;
        
        /// <summary>
        /// pnlReviewAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlReviewAlert;
        
        /// <summary>
        /// lblReviewAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReviewAlert;
        
        /// <summary>
        /// ddlRating control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRating;
        
        /// <summary>
        /// txtReviewText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReviewText;
        
        /// <summary>
        /// btnSubmitReview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmitReview;
        
        /// <summary>
        /// rptReviews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptReviews;
        
        /// <summary>
        /// pnlNoReviews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoReviews;
        
        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;
    }
}
