// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CYPHER.Pages {
    
    /// <summary>
    /// Watches class
    /// </summary>
    public partial class Watches {
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;
        
        /// <summary>
        /// rblCategories control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblCategories;
        
        /// <summary>
        /// rblBrands control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblBrands;
        
        /// <summary>
        /// txtMinPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMinPrice;
        
        /// <summary>
        /// txtMaxPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxPrice;
        
        /// <summary>
        /// btnPriceFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPriceFilter;
        
        /// <summary>
        /// lnkClearFilters control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkClearFilters;
        
        /// <summary>
        /// lblCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCount;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// ddlSort control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        
        /// <summary>
        /// rptProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProducts;
        
        /// <summary>
        /// pnlNoProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoProducts;
    }
}
